version: "3.8"

services:
  web:
    image: python:3.11-slim
    container_name: project-1-web
    restart: always
    working_dir: /app
    volumes:
      - ./app:/app
    command: >
      sh -c "pip install -r requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.project1-http.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project1-http.entrypoints=http
      - traefik.http.routers.project1-http.middlewares=https-redirect
      - traefik.http.routers.project1-https.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.project1-https.entrypoints=https
      - traefik.http.routers.project1-https.tls=true
      - traefik.http.routers.project1-https.tls.certresolver=le
      - traefik.http.routers.project1-https.service=project1-service
      - traefik.http.services.project1-service.loadbalancer.server.port=8000
    networks:
      - traefik-public
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: project1-postgres
    restart: always
    environment:
      POSTGRES_USER: project1_user
      POSTGRES_PASSWORD: project1_pass
      POSTGRES_DB: project1_db
    volumes:
      - project1-db-data:/var/lib/postgresql/data

volumes:
  project1-db-data:

networks:
  traefik-public:
    external: true
